# Generated by Django 5.1.2 on 2024-10-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('PTY_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PTY_FirstName', models.CharField(max_length=255)),
                ('PTY_LastName', models.CharField(max_length=255)),
                ('PTY_Phone', models.CharField(max_length=20)),
                ('PTY_SSN', models.CharField(max_length=20)),
                ('PTY_Gender', models.CharField(max_length=10)),
                ('PTY_Age', models.IntegerField()),
            ],
        ),
    ]
