# Generated by Django 5.1.2 on 2024-10-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='party',
            table='OPT_Party',
        ),
    ]
